 # Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/hammerhead/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/gtexslte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
	vendor/samsung/gtexslte/proprietary/lib/liblsc.so:system/lib/liblsc.so \
	vendor/samsung/gtexslte/proprietary/lib/libcalibration.so:system/lib/libcalibration.so \
	vendor/samsung/gtexslte/proprietary/lib/libsecure_storage.so:system/lib/libsecure_storage.so \
	vendor/samsung/gtexslte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
	vendor/samsung/gtexslte/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
	vendor/samsung/gtexslte/proprietary/lib/libwvm.so:system/lib/libwvm.so \
	vendor/samsung/gtexslte/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
	vendor/samsung/gtexslte/proprietary/lib/libiwnpi.so:system/lib/libiwnpi.so \
	vendor/samsung/gtexslte/proprietary/lib/libengbt.so:system/lib/libengbt.so \
	vendor/samsung/gtexslte/proprietary/lib/libmemoryheapion.so:system/lib/libmemoryheapion.so \
	vendor/samsung/gtexslte/proprietary/lib/libynoise.so:system/lib/libynoise.so \
	vendor/samsung/gtexslte/proprietary/lib/libsprdlsc.so:system/lib/libsprdlsc.so \
	vendor/samsung/gtexslte/proprietary/lib/libspaf.so:system/lib/libspaf.so \
	vendor/samsung/gtexslte/proprietary/lib/libsft_af_ctrl.so:system/lib/libsft_af_ctrl.so \
	vendor/samsung/gtexslte/proprietary/lib/liblsc.so:system/lib/liblsc.so \
	vendor/samsung/gtexslte/proprietary/lib/libdeflicker.so:system/lib/libdeflicker.so \
	vendor/samsung/gtexslte/proprietary/lib/libcalibration.so:system/lib/libcalibration.so \
	vendor/samsung/gtexslte/proprietary/lib/libawb.so:system/lib/libawb.so \
	vendor/samsung/gtexslte/proprietary/lib/libae.so:system/lib/libae.so \
	vendor/samsung/gtexslte/proprietary/lib/libAl_Awb_v2.so:system/lib/libAl_Awb_v2.so \
	vendor/samsung/gtexslte/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/gtexslte/proprietary/bin/refnotify:system/bin/refnotify \
	vendor/samsung/gtexslte/proprietary/bin/rild:system/bin/rild \
	vendor/samsung/gtexslte/proprietary/bin/download:system/bin/download \
	vendor/samsung/gtexslte/proprietary/bin/cp_diskserver:system/bin/cp_diskserver \
	vendor/samsung/gtexslte/proprietary/bin/modem_control:system/bin/modem_control \
	vendor/samsung/gtexslte/proprietary/bin/modemd:system/bin/modemd \
	vendor/samsung/gtexslte/proprietary/bin/wcnd:system/bin/wcnd \
	vendor/samsung/gtexslte/proprietary/bin/wcnd_cli:system/bin/wcnd_cli \
	vendor/samsung/gtexslte/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
	vendor/samsung/gtexslte/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
 	vendor/samsung/gtexslte/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
	vendor/samsung/gtexslte/proprietary/lib/libeng-audio.so:system/lib/libeng-audio.so \
	vendor/samsung/gtexslte/proprietary/lib/libefuse.so:system/lib/libefuse.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
  vendor/samsung/gtexslte/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
	vendor/samsung/gtexslte/proprietary/lib/libbm.so:system/lib/libbm.so \
	vendor/samsung/gtexslte/proprietary/lib/libaf_running.so:system/lib/libaf_running.so \
	vendor/samsung/gtexslte/proprietary/lib/libAF.so:system/lib/libAF.so \
	vendor/samsung/gtexslte/proprietary/lib/libaf_tune.so:system/lib/libaf_tune.so \
	vendor/samsung/gtexslte/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
	vendor/samsung/gtexslte/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
	vendor/samsung/gtexslte/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/samsung/gtexslte/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
	vendor/samsung/gtexslte/proprietary/bin/engpc:system/bin/engpc \
	vendor/samsung/gtexslte/proprietary/bin/batterysrv:system/bin/batterysrv \
	vendor/samsung/gtexslte/proprietary/bin/wlandutservice:system/bin/wlandutservice \
	vendor/samsung/gtexslte/proprietary/bin/macloader:system/bin/macloader \
	vendor/samsung/gtexslte/proprietary/bin/mfgloader:system/bin/mfgloader \
	vendor/samsung/gtexslte/proprietary/lib/libatparser.so:system/lib/libatparser.so \
	vendor/samsung/gtexslte/proprietary/bin/at_distributor:system/bin/at_distributor \
	vendor/samsung/gtexslte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/samsung/gtexslte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
	vendor/samsung/gtexslte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	vendor/samsung/gtexslte/proprietary/etc/firmware/sc2331_fdl.bin:system/etc/firmware/sc2331_fdl.bin \
	vendor/samsung/gtexslte/proprietary/etc/firmware/sc2331_fw.bin:system/etc/firmware/sc2331_fw.bin \
	vendor/samsung/gtexslte/proprietary/etc/audio_para:system/etc/audio_para \
	vendor/samsung/gtexslte/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml \
	vendor/samsung/gtexslte/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
	vendor/samsung/gtexslte/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
	vendor/samsung/gtexslte/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
	vendor/samsung/gtexslte/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
	vendor/samsung/gtexslte/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
	vendor/samsung/gtexslte/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so
	# vendor/samsung/gtexslte/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
	# vendor/samsung/gtexslte/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/lights.sc8830.so:system/lib/hw/lights.sc8830.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/power.sc8830.so:system/lib/hw/power.sc8830.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
	# vendor/samsung/gtexslte/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so
